### ISSUE TITLE
Could not find a package configuration file provided by "trompeloeil"

### ISSUE THREAD

**Issue by apollomok** [offa/influxdb-cxx#104]
I reached this error when I am trying to "cmake" on my mac.
Did I miss any step?

-- The CXX compiler identification is AppleClang 10.0.0.10001044
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ~~~ influxdb-cxx v0.6.7 ~~~
-- Build Type : RelWithDebInfo
-- Boost support : ON
-- Unit Tests : ON
-- System Tests : ON
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found CURL: /opt/local/lib/libcurl.dylib (found version "7.54.0")  
-- Found Boost: /usr/local/lib/cmake/Boost-1.76.0/BoostConfig.cmake (found version "1.76.0") found components: system 
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
CMake Error at test/CMakeLists.txt:3 (find_package):
  By not providing "Findtrompeloeil.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "trompeloeil", but CMake did not find one.

  Could not find a package configuration file provided by "trompeloeil" with
  any of the following names:

    trompeloeilConfig.cmake
    trompeloeil-config.cmake

  Add the installation prefix of "trompeloeil" to CMAKE_PREFIX_PATH or set
  "trompeloeil_DIR" to a directory containing one of the above files.  If
  "trompeloeil" provides a separate development package or SDK, be sure it
  has been installed.

-- Configuring incomplete, errors occurred!

**Comment by offa** [comment]
Do you have Trompeloeil installed? If you don't need the tests but only the library you can disable them too (option: `INFLUXCXX_TESTING`).

**Comment by offa** [comment]
Is this still an issue @apollomok ?

**Comment by amirabas-kz** [comment]
This issue could be easily resolved by following instruction:
`
git clone https://github.com/rollbear/trompeloeil.git
cd trompeloeil
mkdir build ; cd build
cmake -G "Unix Makefiles" ..
sudo cmake --build . --target install
`
