### ISSUE TITLE
Dead-end when batching is enabled and a BadRequest thrown 

### ISSUE THREAD

**Issue by acaballero** [offa/influxdb-cxx#105]
Hello @offa,

Imagine this scenario:

- Batching is enabled with a size of, say, N points.
- One of the points data is bad and generates a BadRequest from InfluxDb.

Since the exception is not being captured at the library, the buffer won't be cleared (mPointBatch.clear() won't be reached). The client may capture the exception, but it is unable to clear the buffer from the outside.

Upcoming calls to 'write' add the point to the buffer (it has now N+1 points) which is tried to be sent again but, as the (bad) point is still there, the BadRequest is raised again. 

This will repeat from there on, until the batch serializes to a packet which size is bigger than INFLUXDB_HTTP_MAX_BODY_SIZE, generating another type of BadRequest exception. A 413 (Request entity too large).

While I don't think it's the responsibility of the library to recover from such a situation by itself (capturing the BadRequest and dropping the current batch), I miss a way to let the client recover from it. For example:

- The library exposes a (copy) of mPointBath in, say, a getBatch method.
- The library exposes a dropBatch to clear the batch.
- The client captures a BadRequest exception, having the opportunity to:
   - Get a copy of the problematic batch.
   - Ask the library to clear the current batch.
   - Set mBatchSize=0 by calling batchOf.
   - Write the recovered batch (one by one) discarding the BadRequest that will be thrown when the bad point is sent.
   - Set back the previous mBatchSize.

This way, we have been able to send all but the bad points. Or, if preferred, discard the batch and go on.

Does this make sense to you?

**Comment by offa** [comment]
We should avoid to expose to many internal implementation details or state here. Solution 2 sounds good to me, adding a method to clear the batch may become handy in other situations too.

**Comment by acaballero** [comment]
Great. Maybe a hybrid like a std::vector<Point> resetBatch() method returning the current state of the buffer wouldn't expose so much of the internals.

**Comment by offa** [comment]
Returning a copy of the batch requires a copy and may not be necessary for some use cases. Should the internal batch representation change it needs a transformation into the vector format again.

**Comment by offa** [comment]
Branch merged to master.

**Comment by offa** [comment]
I close here since the method is available now. Feel free to reopen if there's anything missing. :-)
