### ISSUE TITLE
DB Authentication with Influxdb Client Library in C++ 

### ISSUE THREAD

**Issue by amirabas-kz** [offa/influxdb-cxx#109]
I am trying to do a simple write via provided example.
I encounter following error:
`terminate called after throwing an instance of 'influxdb::BadRequest'
  what():  influx-cxx [treatCurlResponse]: Bad request: 401 `
It seems this is an authentication issue. As I didn't provide any token in my code:

```
#include <InfluxDBFactory.h>
int main() {
// Provide complete URI
	auto influxdb = influxdb::InfluxDBFactory::Get("http://influxd:12345678@localhost:8086?db=newdb");
	influxdb->write(influxdb::Point{"test"}
  	.addField("value", 10)
  	.addTag("host", "localhost"));
	return 0;
}
```

Would you please help me with my code and the method I can do a simple write?
How do I find the db name? How do I insert my token into the code?

**Comment by offa** [comment]
> How do I find the db name?

Using an influxdb shell: `show databases`

Does the *influxd* user exist and has proper permissions on the database?

**Comment by amirabas-kz** [comment]
Thanks for your support. I am using influxdb 2.1, thus, there is no DB name in it. As I know, there is only bucket and organization, right? So there is no `show databases` command.
But, the influx user exists and has full access token.

My information is as follows:

- Username: influxd
- Password: 12345678
- Bucket Name: mydb

So, here is my code:

```
#include <InfluxDBFactory.h>

int main() {
	// Provide complete URI
	auto influxdb = influxdb::InfluxDBFactory::Get("http://influxd:12345678@localhost:8086?db=mydb");
	influxdb->write(influxdb::Point{"test"}
  	.addField("value", 10)
  	.addTag("host", "localhost"));
	return 0;
}
```

Did I fill the URL correctly?

**Comment by offa** [comment]
> I am using influxdb 2.1, does this library support v2.1?

Not yet unfortunately.

It seems there's a [1.x backwards compatible API](https://docs.influxdata.com/influxdb/v2.0/reference/api/influxdb-1x/) though. 

Is the password an actual password or API token? It seems there's a difference ([see remarks](https://docs.influxdata.com/influxdb/v2.0/reference/api/influxdb-1x/#password-or-token)).

**Comment by amirabas-kz** [comment]
I downgraded my influxdb to v1.8 and used your library successfully.
Thanks.

`
Ubuntu 20.04 LTS
Influx 1.8.10 - amd64
`
