### ISSUE TITLE
Use influxdb-cxx library in other programs

### ISSUE THREAD

**Issue by amirabas-kz** [offa/influxdb-cxx#110]
In the case I want to use the following program separately, 
```
auto influxdb = influxdb::InfluxDBFactory::Get("http://localhost:8086?db=test");
influxdb->write(influxdb::Point{"test"}.addField("value", 10).addTag("host", "localhost")
```
I use your provided cmake file:

```
project(example)

find_package(InfluxDB)

add_executable(example-influx main.cpp)
target_link_libraries(example-influx PRIVATE InfluxData::InfluxDB)

```

But what about using it in other projects? I have a project that has it's own simple make file.  How can I integrate your CMAKE file into my MAKEFILE?

My MakeFile:
```
all: 
	g++ -pthread -std=c++11 -w -o db \
	influxdb_controller.cpp \
	listener.cpp \
	db_daemon.cpp \
	session.cpp  -lrt 


```

**Comment by offa** [comment]
Instead of integrating the cmake file, I guess it's easier to link the library directly, not involving CMake at all.

Typically by using `-lInfluxDB`. If the lib isn't installed to an available search path add these: `-L<Path to lib directory>` and `-I<Path to header directory>`.

**Comment by offa** [comment]
Does this solve your problem @amirabas-kz

**Comment by amirabas-kz** [comment]
Absolutely YES!
Thanks for your collaboration and attention.

**Comment by efenaty** [comment]
> Instead of integrating the cmake file, I guess it's easier to link the library directly, not involving CMake at all.
> 
> Typically by using `-lInfluxDB`. If the lib isn't installed to an available search path add these: `-L<Path to lib directory>` and `-I<Path to header directory>`.

Where should I include this? In my own Cmake file or in the cpp file?

**Comment by amirabas-kz** [comment]
@efenaty 
You must include `-lInfluxDB` into your compilation process, whether your Makefile or your bare g++ compilation:
 `g++ -std=c++17 database.cpp -lInfluxDB`
Note that, this works only if you installed InfluxDB and its library correctly, so that your compiler can detect the InfluxDB library via `-lInfluxDB`.

**Comment by offa** [comment]
_(If possible)_ I recommend using CMake instead of plain makefiles though.
