### ISSUE TITLE
Tutorial and examples on how to use APIs

### ISSUE THREAD

**Issue by pkoosha** [offa/influxdb-cxx#118]
Hi,

I am trying to use your library to be integrated to my C program. 
unfortunately I do not see any tutorial on how to use APIs and examples. Could you please refer me to one?
Thanks.

**Comment by offa** [comment]
The readme contains examples which should cover basic usage. Please see `test/` directory for more.

Let me know, if there's something missing.

**Comment by pkoosha** [comment]
I found some useful examples online but there is not documentation on how to update values or setting retention policy through APIs. If you could add these they would greatly help. Thanks

**Comment by offa** [comment]
There's an API for executing any commands now: https://github.com/offa/influxdb-cxx#execute-cmd
