### ISSUE TITLE
setting multiple timestamps for a point

### ISSUE THREAD

**Issue by pkoosha** [offa/influxdb-cxx#122]
I was wondering if I can set multiple timestamps for a point like start and end and name them.
Also, I like to update the timestamps. How should I do that? 

Thanks

**Comment by offa** [comment]
You can add them as two fields.

**Comment by offa** [comment]
@pkoosha were you able to solve this issue?

**Comment by pkoosha** [comment]
Yes I was able to resolve this issue

Best,
Pouya Kousha

From: offa ***@***.***>
Date: Friday, November 4, 2022 at 1:35 PM
To: offa/influxdb-cxx ***@***.***>
Cc: pkoosha ***@***.***>, Mention ***@***.***>
Subject: Re: [offa/influxdb-cxx] setting multiple timestamps for a point (Issue #122)
@pkoosha were you able to solve this issue? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: <offa/influxdb-cxx/issues/122/1303923312@ github. com> ‍ ‍


@pkoosha<https://urldefense.com/v3/__https:/github.com/pkoosha__;!!KGKeukY!z1_0ifnK5xtUQcNQHBYXK0bIKXJkWzUgaFsjQFnyM_I4i1z3F636Lmo_CFUKFGmeSn3ItOHXq9TakvoHNoZOUei-$> were you able to solve this issue?
