### ISSUE TITLE
Boolean field type

### ISSUE THREAD

**Issue by offa** [offa/influxdb-cxx#125]
Boolean is available too: https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_reference/#data-types

**Comment by ronytigo** [comment]
How do I write a bool type? I tried:
addField("val", "True")
but it looks like it's inserted as a string.
How do I insert different data types?

**Comment by offa** [comment]
The boolean datatype isn't supported yet. But you can try to use a 0 / 1 integer and cast to bool instead.

**Comment by ronytigo** [comment]
Can you please show what you mean?
I tried this:
```
int val = 0;
bool v_bool = !!val;
influx_client->write(influxdb::Point{"meas"}.addField("value", v_bool));
```
But in influx I see it as long.

**Comment by offa** [comment]
You can use the bool directly:

```cpp
bool v_bool{true};
influx_client->write(influxdb::Point{"meas"}.addField("value", v_bool));
```
But yes, until there's native bool support available that's a possible workaround.

**Comment by ronytigo** [comment]
what about strings, is it supported?

**Comment by offa** [comment]
Yes, you can use the types available through [`addField()`](https://github.com/offa/influxdb-cxx/blob/master/include/Point.h#L55).

**Comment by ronytigo** [comment]
```
double test = 3.33;
point.addField("value", test);
```
That didn't work.
This works:
```
int32_t test = 10;
point.addField("value", test);
```
Any idea why?

**Comment by offa** [comment]
> Any idea why?

No. Can you verify that the unit tests pass on your system?

Please stay on topic here, it's not related to implementing bool type.

**Comment by ronytigo** [comment]
Can you please tell me how I run the unit tests?
Should I open a new issue?

**Comment by offa** [comment]
If it's not related to bool support, yes, please.
