### ISSUE TITLE
Factory has no option for proxies

### ISSUE THREAD

**Issue by nwotero** [offa/influxdb-cxx#127]
The python client for InfluxDB allows the user to specify proxies, or None to not use a proxy. The InfluxDBFactory does not provide this option. This is important for anyone working behind a proxy.

**Comment by offa** [comment]
Thanks for the suggestion.

According to docs the related options are:

- [`CURLOPT_PROXY`](https://curl.se/libcurl/c/CURLOPT_PROXY.html)
- [`CURLOPT_PROXYUSERNAME`](https://curl.se/libcurl/c/CURLOPT_PROXYUSERNAME.html) / [`CURLOPT_PROXYPASSWORD`](https://curl.se/libcurl/c/CURLOPT_PROXYPASSWORD.html)

In the meantime you can use `http_proxy` env (though authentication seems unsupported that way).

**Comment by nwotero** [comment]
Thanks for the suggestion!

**Comment by offa** [comment]
I have implemented a prototype in ` 127-proxy_support `, but don't have a proxy around at the moment. Could you give it a try?

**Comment by nwotero** [comment]
Yes I can, I will let you know the results. Thank you for making this!

**Comment by nwotero** [comment]
This worked for me, thank you!

**Comment by offa** [comment]
Thank you! I'm going to merge it then! :-)

**Comment by nwotero** [comment]
Yes, I can test it. Thank you!
