### ISSUE TITLE
batch write timeout

### ISSUE THREAD

**Issue by pkoosha** [offa/influxdb-cxx#138]
I have been trying to do batch writes to InfluxDB-cxx with batch size of 50,000. I noticed that the first few write series will go through with increased writing time. Then once it hits more than 5 minutes, I see this error bellow which is very generic and doesn't tell me much. Could you help me?

``` 
terminate called after throwing an instance of 'influxdb::BadRequest'
  what():  influx-cxx [treatCurlResponse]: Bad request: 413
Aborted
```

I have increased the timeout of coordinator to 30m

**Comment by offa** [comment]
> I have been trying to do batch writes to InfluxDB-cxx with batch size of 50,000. I noticed that the first few write series will go through with increased writing time. 

Can the server handle that much data between batches?

> Then once it hits more than 5 minutes, I see this error bellow which is very generic and doesn't tell me much. Could you help me?

The error message is written by the underlying Curl library. However the status code 413 helps here:

> The 413 (Content Too Large) status code indicates that the server is refusing to process a request because the request content is larger than the server is willing or able to process.

(https://httpwg.org/specs/rfc9110.html#status.413)

Influxdb has a default limit of 25000000 (`max-body-size`); once the limit is exceeded you'll get a _413_ response ([docs](https://docs.influxdata.com/influxdb/v1.8/administration/config/)).

What you can do:

- Reduce the batch size (or data) so batches fit into body size
- Increase or disable body size limit – please make sure you understand the implications though.

**Comment by offa** [comment]
I'm going to close here as it's not an issue of this project. Please feel free to reopen if you need more help.

**Comment by pkoosha** [comment]
Sounds good! I was able to alleviate the issue after increasing the max-body-size


Best,
Pouya Kousha

From: offa ***@***.***>
Date: Tuesday, November 22, 2022 at 10:59 AM
To: offa/influxdb-cxx ***@***.***>
Cc: pkoosha ***@***.***>, Author ***@***.***>
Subject: Re: [offa/influxdb-cxx] batch write timeout (Issue #138)
I'm going to close here as it's not an issue of this project. Please feel free to reopen if you need more help. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread. Message


I'm going to close here as it's not an issue of this project. Please feel free to reopen if you need more help.

**Comment by offa** [comment]
Thanks for the feedback! :-)
