### ISSUE TITLE
Delete record by time

### ISSUE THREAD

**Issue by AIGirl10** [offa/influxdb-cxx#143]
It is easy to delete record by time using CLI interface, 
```sh
delete from imagetable where time='2022-11-16T19:42:41.945508272Z'
```
but I am not able to figure out how to do the same with influxdb-cxx. i.e. not able to access the time through C++ interface.
e.g. Tags can be accessed with function `points[0].getTags()` but how to access the time ?  

Have already tried to access it with `points[0].getTimestamp()` but not able to print it in this format in C++ `2022-11-17T03:37:25.934547412Z`

can anyone please help ?

**Comment by offa** [comment]
I have just merged #141 which supports generic queries (#137; examples / docs follow). You can pass the query to `execute()` method now.

**Comment by AIGirl10** [comment]
@offa 

Thanks for the reply, but I have problem in reading time in this format `2022-11-17T03:37:25.934547412Z` from database, would you please help you with it ?

**Comment by offa** [comment]
Can you provide more details?

**Comment by offa** [comment]
ping @AIGirl10
