### ISSUE TITLE
> I am using influxdb 2.1, does this library support v2.1?

### ISSUE THREAD

**Issue by ronytigo** [offa/influxdb-cxx#147]
> I am using influxdb 2.1, does this library support v2.1?

Not yet unfortunately.

It seems there's a [1.x backwards compatible API](https://docs.influxdata.com/influxdb/v2.0/reference/api/influxdb-1x/) though. 

Is the password an actual password or API token? It seems there's a difference ([see remarks](https://docs.influxdata.com/influxdb/v2.0/reference/api/influxdb-1x/#password-or-token)) between both.

_Originally posted by @offa in https://github.com/offa/influxdb-cxx/issues/109#issuecomment-1022332344_
      

Is it possible to use the "InfluxDB 1.x compatibility endpoints"?
How can I run this using the library?
curl --get "http://localhost:8086" \
  --header "Authorization: Token INFLUX_API_TOKEN" \
  --header 'Content-type: application/json' \
  --data-urlencode "db=mydb" \
  --data-urlencode "q=SELECT * FROM cpu_usage"

**Comment by offa** [comment]
The v2.x support is still somewhat limited and I do not have much experience myself here.
I guess it should work with the compatibility API but you have to use credentials as mentioned in the linked docs.

**Comment by saukijan** [comment]
So would passing `"http://username:password@localhost:8086?db=test"` to `influxdb::InfluxDBFactory::Get()` work for influxdb 2.x?

Personally, I am using InfluxDB v2.5.1 on Debian 11 and running 

```cpp
#include <InfluxDBFactory.h>
#include <string>
#include <iostream>

using namespace std;

int main() {
  auto influxdb = influxdb::InfluxDBFactory::Get("http://username:password@localhost:8086?db=test");
 
  const auto response = influxdb->execute("SHOW DATABASES");

  cout << "Show Databases query response: " << response << endl;
 
  return 0;
}
```

results in a `influxdb::BadRequest` exception: 

```
terminate called after throwing an instance of 'influxdb::BadRequest'
  what():  influx-cxx [treatCurlResponse]: Bad request: 401
```

I also tried writing some data into the InfluxDB with

```cpp
#include <InfluxDBFactory.h>
#include <string>
#include <iostream>

using namespace std;

int main() {
  auto influxdb = influxdb::InfluxDBFactory::Get("http://username:password@localhost:8086?db=test");
 
  cout << "Adding test tag with field value" << endl;

  influxdb->addGlobalTag("test", "value");

  cout << "Writing data to test bucket, test tag, value field" << endl;

  try {
    influxdb->write(influxdb::Point{"test"}.addField("value", 1));
  } catch (exception& ex) {
    cerr << "Caught an exception while writing data to test bucket. Exception: "
         << ex.what() << endl;
  }

  cout << "Reading data from test bucket" << endl;

  auto points = influxdb->query("SELECT * FROM test");
  if (!points.empty()) {
    for (auto const& point : points) {
      cout << point.getName() << " " << point.getTags() << " "
           << point.getFields() << endl;
    }
  } else {
    cout << "No data found in test bucket" << endl;
  }
  return 0;
}
```

which results in

```
Adding test tag with field value
Writing data to test bucket, test tag, value field
Caught an exception while writing data to test bucket. Exception: influx-cxx [treatCurlResponse]: Bad request: 401
Reading data from test bucket
terminate called after throwing an instance of 'influxdb::BadRequest'
  what():  influx-cxx [treatCurlResponse]: Bad request: 401
Aborted
```

Of course, no data on influxdb data explorer page. So it seems that this library does not work with 2.x releases...

I might have misconfigured something when installing influxdb, thus causing all of these issues, but it would be really nice to get a confirmation on this. 

Could anyone with check if the above examples work on any 2.x release?

**Comment by offa** [comment]
I would expect this to depend on the type of user created.

_(This is based on infos I have in the [docs](https://docs.influxdata.com/influxdb/v2.0/reference/api/influxdb-1x/#password-or-token))_

If I understand this correctly:

> username: 1.x username (this is separate from the UI login username)

There's a dedicated user type for the v1.x backend. So "normal" users wont work, but need a special user type created (eg. via [auth create](https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/v1/auth/create/)).

**Comment by saukijan** [comment]
thanks for the quick response @offa, I'll check this later today and let you know the results!

**Comment by saukijan** [comment]
Hey @offa, yup it works now. All I had to do was create a v1 auth user by running the following: 

```bash
influx v1 auth create --read-bucket ${BUCKET_ID} --write-bucket ${BUCKET_ID} --username ${USERNAME} --password ${PASSWORD}
```

I think it would be really helpful if you added a new section to the [README.md](https://github.com/offa/influxdb-cxx/blob/master/README.md), quickly covering v2.x support as well as a copy-paste command to create a v1 auth token and a link to [v1 Auth Creation](https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/v1/auth/create/) for further reading. 

Thanks again for your work 😉

**Comment by offa** [comment]
Added, thanks! :-)

**Comment by Lithimlin** [comment]
It would be helpful to clarify in the examples that the `username:password` bit is required for those who aren't familiar with InfluxDB yet, especially with v1
