### ISSUE TITLE
string and double not working

### ISSUE THREAD

**Issue by ronytigo** [offa/influxdb-cxx#161]
```
double test = 3.33;
point.addField("value", test);
```
and
```
point.addField("value", "test");
```
don't work.
```
int32_t test = 10;
point.addField("value", test);
```
Does work and I see the data in the db.

**Comment by offa** [comment]
(As mentioned in the other ticket) Please run verify the unit tests work on your system (eg. `make unitttest`). There are tests for all supported types.

Do you have a minimal example to reproduce the issue? And what kind of error do you get?

**Comment by ronytigo** [comment]
I tried `make unitttest` (sure it's with 3 't'?) in the root folder and in the test folder. I get:
make: *** No rule to make target 'unittest'.  Stop.

**Comment by ronytigo** [comment]
```influxdb::Point point = influxdb::Point{"meas"};
double test = 3.33;
point.addField("value", test);
influx_client->write(std::move(point));
```
influx-cxx [treatCurlResponse]: Bad request: 422

**Comment by ronytigo** [comment]
I print the lines in the batch before sending them:
_1ms_AuxDINT,gateway=192.168.1.2/1,plc_name=plc,level0=_1ms_AuxDINT value=3.333000000000000185 1674934678100026258
_1ms_AuxDINT,gateway=192.168.1.2/1,plc_name=plc,level0=_1ms_AuxDINT value=3.333000000000000185 1674934678110483221
_1ms_AuxDINT,gateway=192.168.1.2/1,plc_name=plc,level0=_1ms_AuxDINT value=3.333000000000000185 1674934678120823930

**Comment by ronytigo** [comment]
I print the lines in the batch before sending them:
```
meas value=3.333000000000000185 1674934678110483221
meas value=3.333000000000000185 1674934678120823930
```

**Comment by offa** [comment]
> I tried `make unitttest` (sure it's with 3 't'?) in the root folder and in the test folder. I get: make: *** No rule to make target 'unittest'. Stop.

You are right, it's unittest (with 2x 't') :-)

It's necessary to run it within your build directory as it's a make target. Tests need to be enabled (aka. not disabled) btw.

**Comment by offa** [comment]
One more thing you should try: Write to new an completely fresh database.

**Comment by ronytigo** [comment]
yeah I also tried unittest and also from my build folder, but I don't know how to not disable the tests. I just cloned the project and added this to my CMakeLists.txt file:
```
add_subdirectory(deps/influxdb-cxx)
target_link_libraries(rony_test PRIVATE InfluxData::InfluxDB)
set(INFLUXCXX_WITH_BOOST OFF)
```

**Comment by offa** [comment]
I see, tests are disabled if included as subdirectory. So it might be easier to test a minimal example with a fresh database first.

**Comment by ronytigo** [comment]
writing to a new bucket worked for double and didn't work for string. then another new bucket worked for string.
why is that? and how can it be fixed?

**Comment by offa** [comment]
Are you mixing types within the same field?

**Comment by ronytigo** [comment]
ah, yes, I use the same measurement for the different types. I'll try different ones!

**Comment by ronytigo** [comment]
seems to work, thanks!
