### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by ronytigo** [offa/influxdb-cxx#162]
I want to insert data to the db from multiple threads.
Should I use a different influxdb::InfluxDB for each thread or I can use a global one?

**Comment by offa** [comment]
This depends on your use cases. The library itself doesn't guarantee thread safety.

**Comment by ronytigo** [comment]
The use case is calling write(point), using batch, from some threads.

**Comment by offa** [comment]
Batches aren't synchronized across threads (nor are other operations). You can implement your own reader-writer queue though.

**Comment by ronytesler** [comment]
Will using `auto influxdb = influxdb::InfluxDBFactory::Get(...)` in each thread work?

**Comment by offa** [comment]
I think so; every thread works on it's own instance.

**Comment by offa** [comment]
I close here as the main question has (hopefully) been answered. Please feel free to reopen if you have further questions regarding this topic.
