### ISSUE TITLE
value in line protocol is 'nan'

### ISSUE THREAD

**Issue by ronytigo** [offa/influxdb-cxx#167]
```
float val = plc_tag_get_float32(tag, 1000);
point.addField("val", val);
```
In the line protocol I get `...val=nan...`
What am I doing wrong?

**Comment by offa** [comment]
Please provide more information how to reproduce the problem, eg. a minimal _runnable_ code example.

**Comment by offa** [comment]
I'm closing here, as this problem isn't reproducible. Feel free to reopen if you still experience it, but please include more details.
