### ISSUE TITLE
Missing pthread symbols on Clang 15 with Boost 1.71.0

### ISSUE THREAD

**Issue by offa** [offa/influxdb-cxx#173]
As mentioned in #172 Clang 15 with Boost 1.71.0 fails due to missing pthread symbols:

```
/usr/bin/ld: ../src/CMakeFiles/InfluxDB-BoostSupport.dir/UDP.cxx.o: undefined reference to symbol 'pthread_condattr_setclock@@GLIBC_2.3.3'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

[build.log](https://github.com/offa/influxdb-cxx/files/10826296/build.log)

**Comment by offa** [comment]
At least Boost and Curl (via cpr) seem to pull threads in.

**Comment by offa** [comment]
@simonaldrich Clang 15 / Boost 1.71 seems not enough to reproduce the issue. However, there are some dependencies that may require thread symbols.

I have added threads to all unit tests; if you have some spare time, could you give `173-threads_symbols` branch a try?

**Comment by saldrich-adx** [comment]
> I have added threads to all unit tests; if you have some spare time, could you give `173-threads_symbols` branch a try?

That branch [builds](https://github.com/offa/influxdb-cxx/files/10838918/build-173-threads-symbols.txt) and executes the `unittest` target successfully for me :slightly_smiling_face:

**Comment by offa** [comment]
Thanks for your feedback!
