### ISSUE TITLE
TCP URI protocol Error

### ISSUE THREAD

**Issue by Amega328** [offa/influxdb-cxx#186]
when passing the following URL using TCP :
auto influxdb = influxdb::InfluxDBFactory::Get("tcp://UserName:Password@localhost:8086?db=DatabaseName"); 

I receive the following Error:

terminate called after throwing an instance of 'influxdb::InfluxDBException'
  what():  write_some: Connection reset by peer
Aborted

However when using http instead of tcp it works.

Do I need to change any configuration in influxdb config file to use TCP.

InfluxDB version:  1.8.10
Boost Version: 1.74.0.3

Thanks.

**Comment by offa** [comment]
TCP isn't supported by Influxdb itself but was introduced to send data to compatible databases (namely Questdb).

**Comment by offa** [comment]
I'm closing here, the question seems answered. Please feel free to reopen if there are issues left.
