### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by thangheo** [offa/influxdb-cxx#202]
Linux : after install cpr and build and voila, can't find cmake for cpr, then after adding cprConfig.cmake to /usr/local/cpr/..  then a bunch of other dependencies error appear.
I bet those people who contribute and create this project mostly use chatgpt without know what actualy is dependencies.
CMake Error at test/CMakeLists.txt:3 (find_package):
  By not providing "Findtrompeloeil.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "trompeloeil", but CMake did not find one.

  Could not find a package configuration file provided by "trompeloeil" with
  any of the following names:

    trompeloeilConfig.cmake
    trompeloeil-config.cmake

  Add the installation prefix of "trompeloeil" to CMAKE_PREFIX_PATH or set
  "trompeloeil_DIR" to a directory containing one of the above files.  If
  "trompeloeil" provides a separate development package or SDK, be sure it
  has been installed.

**Comment by offa** [comment]
Trompeloeil is needed for tests only. If you are interested in consuming the library but don't want the tests, you can build it with `-DINFLUXCXX_TESTING=OFF`; if you need the tests you have to install trompeloeil and catch2.


> I bet those people who contribute and create this project mostly use chatgpt without know what actualy is dependencies.

Why?

**Comment by thangheo** [comment]
I have to build cpr with this flag  : cmake .. -DCPR_USE_SYSTEM_CURL=ON, without this flag I cant build influxdb-cxx.

**Comment by thangheo** [comment]
I use redis anyway!thanks for support
