### ISSUE TITLE
(400) Bad Request when inserting a point with an integer field or a string field

### ISSUE THREAD

**Issue by Globostofo** [offa/influxdb-cxx#208]
I have this error when I try to insert a point containing an integer field or a string field.

```cpp
auto db = influxdb::InfluxDBFactory::Get("http://127.0.0.1:8086?db=MY_TEST_DB");
db->createDatabaseIfNotExists();
db->write(influxdb::Point{"cpu"}.addField("value", 5));
// db->write(influxdb::Point{"cpu"}.addField("value", "5")); // <-- or with a string
```

```
terminate called after throwing an instance of 'influxdb::InfluxDBException'
  what():  Request failed: (400) Bad Request
Aborted (core dumped)
```

I don't know what's causing it, all I can say is that I can correctly fetch data or insert double values in the database.

I'm using :
- `influxdb-cxx` 0.7.1
- `cpr` 1.10.4
- `influxdb` 1.8.10
- `gcc/g++` 11.4.0
- `cmake` 3.22.1
- in a `Kubuntu 22.04.3` Virutal Machine

Thanks in advance for your help.

**Comment by Globostofo** [comment]
Oof, just read this https://github.com/offa/influxdb-cxx/issues/161#issuecomment-1407473549, and now it works fine...

I guess next time I'll read all the issues before posting one :')
Is there an explanation of why a new database is needed? I don't want to run into this bug again in production.

**Comment by offa** [comment]
>  Is there an explanation of why a new database is needed? I don't want to run into this bug again in production.

The problem back then wasn't related to a new database but using different types on the same measurement (if I remember correctly).

**Comment by Globostofo** [comment]
Oh yes! I did that without realising it.

Perhaps it would be a good idea to improve the exceptions to make them more explicit?

**Comment by offa** [comment]
Exception code and message are provided by CPR and thrown as a new type. It would be possible to get some additional information from the response which would look like this:

> {"error":"partial write: field type
  conflict: input field \"value\" on measurement \"x\" is type string, already
  exists as type integer dropped=1"}

It might be  somewhat verbose, but would help to identify the underlying issue :+1:.
