### ISSUE TITLE
Issues with TCP transport

### ISSUE THREAD

**Issue by lvn2007** [offa/influxdb-cxx#259]
It seems that with Boost installed, TCP transport was not usable and had to fall back to HTTP.
The following calls will result in an error if use TCP but works fine if using HTTP:

```cpp
auto influxdb = influxdb::InfluxDBFactory::Get("tcp://localhost:8086?db=test");
influxdb->createDatabaseIfNotExists();
influxdb->write(influxdb::Point{"test"}
  .addField("value", 10)
  .addTag("host", "localhost")
);
```

**Comment by offa** [comment]
Please add some more information of your system. What version of this library and influxdb (1.x / 2.x) are you using?

Please not, TCP transport is _not_ supported by influxdb, but eg. questdb.

**Comment by lvn2007** [comment]
I'm using InfluxDB v1.6.7~rc0 and latest version of influxcxx from master branch.

**Comment by offa** [comment]
Influxddb doesn't support TCP transport itself. Thus I recommend HTTP. If you need TCP you could consider QuestDb instead.

**Comment by offa** [comment]
Indeed, the readme isn't clear on this. I have noted it for improvement (#188).
