### ISSUE TITLE
Certificate authenticity is not checked in HTTPS transport

### ISSUE THREAD

**Issue by fmoessbauer** [offa/influxdb-cxx#42]
In the HTTPS backend, checking the peers origin is explicitly disabled. While this allows to use self-signed-certificates, it also allows man-in-the-middle attacks.

I was able to connect against a local, self-signed influxdb via HTTPs, without getting even a notice on the certificate.

As the project is still in a 0.x version, I don't think we need a CVE here.

A fix can be found in #41.

**Comment by offa** [comment]
I haven't worked through the code myself yet, but this is a severe issue.

**Comment by offa** [comment]
Released as v0.6.3.
