### ISSUE TITLE
Buffering totally broken

### ISSUE THREAD

**Issue by fmoessbauer** [offa/influxdb-cxx#45]
Hi,

when buffering is enabled, unfortunately the buffer queue is never flushed after conversion to the transmission format.
By that, the queue grows to infinity and the same data is send again and again...
Probably the bug was introduced in https://github.com/offa/influxdb-cxx/commit/61e15e1841b44cc1bd2d6d6a5923258da98adf2f

I think, a `mLineProtocolBatch.clear();` [here](https://github.com/offa/influxdb-cxx/blob/master/src/InfluxDB.cxx#L76) would solve the problem.

But nonetheless, there are definitely tests missing to discover these kinds of bugs.
Also it makes me a bit skeptic about the overall quality of this project, as it seems like there slipped some bad PRs into the code.

**Comment by offa** [comment]
Thanks for reporting. It seems I merged a PR too soon … and now there's a cleanup needed.

Regarding tests: Yes, absolutely. Fixing this issue should definitely include proper tests.

**Comment by offa** [comment]
Fixed, the queue is cleared now and there's a unit test.
