### ISSUE TITLE
Use Catch for unit tests?

### ISSUE THREAD

**Issue by offa** [offa/influxdb-cxx#47]
While the current test suites provide integration tests mostly, there's a lack of real unit tests.

At this point I think about using Catch (and Trompeloeil) for writing those.

**Comment by fmoessbauer** [comment]
Just a side-note: Currently the tests are neither idempotent, nor independent of each other. By that:
- the tests cannot be run in parallel (due to access to same database)
- test order matters
- the created database is not removed

**Comment by offa** [comment]
One more annoying thing: Most tests need a running database.

**Comment by offa** [comment]
Continued in #57.
