### ISSUE TITLE
Include the Conan wrapper into the main CMakeLists.txt?

### ISSUE THREAD

**Issue by offa** [offa/influxdb-cxx#53]
Does it make sense to include the Conan wrapper cmake code into the main CMakeLists.txt?

The relevant part consists only of two lines, but the wrapper complicates the build unnecessarily.

Another possible approach: Test whether `conanbuildinfo.cmake` exists; if so, include it and call `conan_basic_setup()`.

#### Benefit:

It simplifies the Conan build and it remains fully optional.

#### Drawback:

It introduces Conan related code – it's still optional though.

CC @steinerthomas

**Comment by steinerthomas** [comment]
As you mentioned as a drawback, some people maybe don't want Conan related code if they use your library. I saw this wrapper injection in the [google benchmark](https://github.com/google/benchmark) library.

Of course the goal should be, to add the library to the [conan-center-index](https://github.com/conan-io/conan-center-index).

**Comment by offa** [comment]
Conan should still be fully optional of course, so it should always be possible to compile without it. Something like [here](https://github.com/cpputest/cpputest/blob/846b0addbfe4353861750b5d0b9cf5274f6c20cf/CMakeLists.txt#L13). Are there any drawbacks using this way?

**Comment by steinerthomas** [comment]
No there are no drawbacks. Pls describe your use case: I think you need it for getting boost binaries from conan-center and you want to call `conan install .`?
I personally don't need this in the CMakeLists, because I'm a consumer of your library and I need the binaries for this lib on our artifactory.
For me as a consumer of this lib, as already mentioned, it would be more important to bring a recipe to the [conan-center-index](https://github.com/conan-io/conan-center-index) and there you'll still have to wrap the conan stuff into a CMake wrapper.

**Comment by offa** [comment]
> No there are no drawbacks. Pls describe your use case: I think you need it for getting boost binaries from conan-center and you want to call conan install .?

Exactly, the main reason for the idea is to simplify the build. However I'm not quite sure if this may interfere with the other cmake generators.

> For me as a consumer of this lib, as already mentioned, it would be more important to bring a recipe to the conan-center-index and there you'll still have to wrap the conan stuff into a CMake wrapper.

That makes sense to me, but before submitting it, I want to improve some things. Unfortunately I can't get Conan to work with Boost and Catch too.

**Comment by steinerthomas** [comment]
> Exactly, the main reason for the idea is to simplify the build. However I'm not quite sure if this may interfere with the other cmake generators.
> 
But the build should also work without conan and with conan you can call `conan create .` and then the `conan_basic_setup` will get injected by the recipe.

> That makes sense to me, but before submitting it, I want to improve some things. Unfortunately I can't get Conan to work with Boost and Catch at the moment too.
> 
I'm looking forward to find it on conan-center-index soon :wink:

**Comment by offa** [comment]
I see, thanks for your help!
