### ISSUE TITLE
Create Database HTTP interface

### ISSUE THREAD

**Issue by gedoensmax** [offa/influxdb-cxx#77]
Is there any way to create a database using the HTTP protocol ? Or to get the actual transport used inside the InfluxDB object? 

(On another note: The lib does not support influxDB2.0 right ?)

**Comment by gedoensmax** [comment]
![grafik](https://user-images.githubusercontent.com/44298237/109562078-3d050680-7ade-11eb-9013-7c12bcfb9f56.png)

Or is the install command the problem ? Because this is all the install command does for me. To get to more in depth commands i would have to copy header files from `src` which sounds wrong.

**Comment by offa** [comment]
Yes, you can use `InfluxDB::createDatabaseIfNotExists()` (supported on HTTP only). The internal transport is not exposed.

> (On another note: The lib does not support influxDB2.0 right ?)

Not officially, but I have it on my todo list already.


> Or is the install command the problem ? Because this is all the install command does for me. To get to more in depth commands i would have to copy header files from src which sounds wrong.

The install command installs public / exported API only, everything in `src/` is implementation only and not intended for client usage. The structure looks OK for me.

**Comment by gedoensmax** [comment]
Ok i am very sorry seems that i was completely mistaken yesterday. Or may it be possible that the last tagged version did not support that yet ? Because i always got an error saying that it was not implemented. (Only Curl installed so Http protocol)

**Comment by offa** [comment]
The method is available since v0.6.0, can you figure out the version you are using (eg. CMakeLists.txt or Git commit)?

**Comment by gedoensmax** [comment]
Yeah i must have messed it up somehow.

**Comment by gedoensmax** [comment]
Ok there definetly is something wrong i was not completely mistaken. So i am building for Windows and Linux - release and debug. If i use 0.6.4 only Release can find the symbol for `InfluxDB::createDatabaseIfNotExists()`. If i use the master it compiles everything but debug build for Windows crashes and throws: `bad allocation` which is not caught by this code snippet 
```
const std::string query = "http://user:password@localhost:8086?db=metrics";
    try
    {
        mConnection = influxdb::InfluxDBFactory::Get(query);
    }
    catch (influxdb::InfluxDBException& e)
    {
        std::cout << e.what() << std::endl;
    }
```
The curl binary i am using is https://curl.se/windows/dl-7.75.0_4/curl-7.75.0_4-win64-mingw.zip.
Ninja version is 1.10.2
cl.exe: Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29337 for x64
CMake version is 3.19.5

**Comment by offa** [comment]
Do I understand this correctly: The issue appears on Linux and Windows (or Windows only?)? Is there any useful information in the `bad_alloc` exception or it's stacktrace?

Can I test the minimal example in two scenarios (not linking any other libraries):

1. The code above compiled as an executable and InfluxdDB is linked
2. The code is compiled as part of this project (eg. by using a `add_executable()`and linking the library)

**Comment by gedoensmax** [comment]
The 0.6.4 issue appears on Win and Linux. Master only has the explained issue on Windows. I tried to find more useful information but as soon as i try to step in on InfluxDBFactory::Get the Exception appears. This is what i think is the weirdest thing and i cannot really explain it. I tried deleting anf starting from scratch but the issue comes up again. The Library is built and Linked via a custom finder for the include dir and the library.

**Comment by gedoensmax** [comment]
I can try to put together a minimal example later today.

**Comment by offa** [comment]
That would be great. Please double check if the correct library is linked, maybe there's another version laying around somewhere.

**Comment by gedoensmax** [comment]
[influx_testing.zip](https://github.com/offa/influxdb-cxx/files/6091732/influx_testing.zip)
If you want to have a look here is a reproducer. I guess there is something wrong with my linking but i did not figure it out yet.

**Comment by offa** [comment]
The project failed to build on my system (Linux) as it copies curl DLLs around.

Please start with a really minimal example, like a simple main with the code above and no additional logic or dependencies. You can then use `ldd` to figure out what's linked actually. Just make sure influxdb and the example are compiled with the same build type – unlike the CMake default the library uses `RelWithDebInfo` if no build type is set explicitly.

**Comment by gedoensmax** [comment]
I just simplified the sample and it ran. Then i executed the binary from the debug build that failed the last days and that worked too. I don't know why but it seems to be somehow ip dependent. If i use localhost, the local IP or the IP within the VPN. All the tests i did today - without changes - apart from the used IP worked. I will just close this again...
