### ISSUE TITLE
Boost required with http transport

### ISSUE THREAD

**Issue by kartsan** [offa/influxdb-cxx#78]
I need to make queries to InfluxDB in my software and I want to avoid Boost because I want to keep the environment small. I thought that influxdb-cxx can work with curl only so I decided to try. However, when I compiled the library in and tested, it didn't work. I was under impression that http url should choose HTTP transport and thus use curl but I wonder if Boost is still required?

Used version: 0.6.4
Compiler: g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

Steps to reproduce:

1. Compile influxdb-cxx library in an environment **without** Boost libraries
2. Make a test program with the code below.

Code:
```
auto idb = influxdb::InfluxDBFactory::Get("http://influxdb:8086?db=testdb");
std::vector<influxdb::Point> points = idb->query("SELECT * FROM test");

```

Expected behaviour:

Points are readable in the `points` vector.

Actual behaviour:

Library throws InfluxDBException exception with the text "influx-cxx [InfluxDB]: Qeury requires Boost" on the query method.

**Comment by offa** [comment]
Unlike writes, Boost is still required for queries unfortunately.  I'll add a remark to the documentation.

Since you are on Ubuntu you don't have to install full boost, but _boost-system_ only. For 18.04 it's `libboost-system1.65-dev` I guess. Alternatively you can use Conan, which doesn't install it system wide.

**Comment by kartsan** [comment]
Ok, thanks for the clarification. I may need to rethink that Boost question in my system now.

**Comment by offa** [comment]
@kartsan Can we close here?

**Comment by kartsan** [comment]
> @kartsan Can we close here?

Yes, I didn't close it yet because you mentioned that you'll make a remark to the documentation.
