### ISSUE TITLE
Vcpkg support

### ISSUE THREAD

**Issue by draveness** [offa/influxdb-cxx#80]
can we support vcpkg and schedule a new release?

**Comment by offa** [comment]
To be honest, I don't have any idea about vcpkg …

What's needed to support it?

Release is no problem. I wanted to change some more things, but those can move into another one – let me know if you need it earlier.

**Comment by draveness** [comment]
I think someone in the vcpkg community would help with this https://github.com/microsoft/vcpkg/issues/16622

**Comment by offa** [comment]
Oh, nice. :+1:  No objections from my side.

**Comment by offa** [comment]
v0.6.5 released.

@draveness since the packaging progress is tracked in the issue linked above, can we close here?

**Comment by draveness** [comment]
Thank you

**Comment by autoantwort** [comment]
I am currently writing the vcpkg port. On which parts of boost do you depends?

**Comment by offa** [comment]
The current version needs boost system only.

**Comment by autoantwort** [comment]
As far as I can see you depend on boost-asio, boost-conversion and boost-property-tree

**Comment by offa** [comment]
That's interesting, boost system is the only component [requested](https://github.com/offa/influxdb-cxx/blob/master/CMakeLists.txt#L82) and [linked](https://github.com/offa/influxdb-cxx/blob/master/src/CMakeLists.txt#L19).

**Comment by autoantwort** [comment]
Yeah because it is the only boost library that you use that is not header only. But header only libs are also dependencies. In vcpkg boost is split in all its sub libs listed [here](https://www.boost.org/doc/libs/1_75_0/) because you rarely depend on all libs. If you depend for example on asio you only have to build the boost libs nessesary for asio but not Boost.Python.

**Comment by offa** [comment]
Nice catch :+1:

**Comment by offa** [comment]
@autoantwort is there a workaround for your packaging issue?

**Comment by autoantwort** [comment]
You can find the PR for vcpkg here: microsoft/vcpkg#16794. I have made the boost support a "feature", so you can opt in it. One Problem is (from [here](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#when-defining-features-explicitly-control-dependencies)): 
> When defining a feature that captures an optional dependency, ensure that the dependency will not be used accidentally when the feature is not explicitly enabled.

That is currently a problem. Your lib searches for boost even is the user don't requested it explicitly. So we need an option to disable the searching for boost. Or an option to explicitly enable it.

**Comment by offa** [comment]
Whether Boost based features are enabled nor not is controlled depending on `find_package()`s success of finding it.

An option like `INFLUXCXX_NO_BOOST` or `…_WITH_BOOST` sounds reasonable here. It makes explicit whether Boost is enabled or disabled, instead of silently deciding what's used.

**Comment by autoantwort** [comment]
I think `INFLUXCXX_WITH_BOOST` is the better option. When the option is set, you can make boost a required component.

**Comment by offa** [comment]
Is there anything left for a new release?

**Comment by autoantwort** [comment]
Not from my side :)

**Comment by offa** [comment]
Released as v0.6.6.
