### ISSUE TITLE
Cannot compile without dependencies

### ISSUE THREAD

**Issue by westminsterflip** [offa/influxdb-cxx#84]
Catch2 and Trompeloeil are unlisted dependencies without which cmake will fail.  Currently I am stuck on this:
 `CMake Error at test/CMakeLists.txt:13 (add_executable):
  Target "BoostSupportTest" links to target "trompeloeil::trompeloeil" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  test/CMakeLists.txt:39 (add_unittest)`
I tried to install trompeloeil but it seems I did something wrong because it can't find it.

**Comment by offa** [comment]
Both are required for tests only. If you just need the library you can use the `INFLUXCXX_TESTING` option to build without them:

```sh
cmake -DINFLUXCXX_TESTING=OFF ..
```

**Comment by westminsterflip** [comment]
Ah, thanks.
