### ISSUE TITLE
Timestamps on a query returned with seconds precision

### ISSUE THREAD

**Issue by pquan** [offa/influxdb-cxx#88]
On simple queries (select * from measurement) I get a precision of 1 second on timestamps. The timestamps in my db are nanoseconds.
This is in VS2019 with influxdb-cxx installed via vcpkg.
Seems a bug, but perhaps I'm not using the library correctly?

**Comment by offa** [comment]
I guess the [time string](https://github.com/offa/influxdb-cxx/blob/master/src/BoostSupport.cxx#L68) used for parsing is second only and doesn't respect finer resolution. Furthermore [`std::get_time()`](https://en.cppreference.com/w/cpp/io/manip/get_time) seems not to support milli- or nanoseconds. 

Just to be sure, can you verify the actual query returns proper nanosecond timestamps?

**Comment by pquan** [comment]
Yes it does return nanosecond. mTimestamp actually contains the nanosecond value, but it's casted down to seconds by the return type. 
```

std::chrono::time_point<std::chrono::system_clock> Point::getTimestamp() const
{
  return mTimestamp;
}
```

Perhaps  use std::chrono::time_point_cast<std::chrono::nanoseconds> ?

**Comment by offa** [comment]
Wait … the received point contains a correct nanosecond timestamp after parsing? Eg. after [this line](https://github.com/offa/influxdb-cxx/blob/master/src/BoostSupport.cxx#L69)?

**Comment by pquan** [comment]
I'm using curl and the http protocol.
I compiled boost support in, but I'm instantiating an object via influxdb factory with the following connesion string: 
```
'http://user:pass@influxhost:8086?db=testdb&precision=ms'
```
I do see the nanosecond precision inside the mTimestamp class attribute. And I see that it's the http protocol that is being used.

**Comment by pquan** [comment]
Cancel my previous comment. My bad. The timestamp from the query is actually seconds.

**Comment by offa** [comment]
No problem :wink:. The current implementation supports only seconds resolution on received points unfortunately.
But it's a good feature, maybe it can be combined with #86.

**Comment by pquan** [comment]
Here the responseString buffer contains the proper timestamp, with millisecond precision, as requested by the connection url.
```
namespace influxdb::internal
{
    std::vector<Point> queryImpl(Transport* transport, const std::string& query)
    {
        const auto response = transport->query(query);
        std::stringstream responseString;
        responseString << response;
```
However
```
timeString >> std::get_time(&tm, "%Y-%m-%dT%H:%M:%SZ");
```
casts it to a second precision.
Since you're actually constructing a chrono object, it might be wise to actually convert the string directly without passing trough a tm structure.

**Comment by pquan** [comment]
> No problem 😉. The current implementation supports only seconds resolution on received points unfortunately.
> But it's a good feature, maybe it can be combined with #86.

Yes, I need it. For instance, I need to log events with a sub-millisecond precision. They arrive in batches of 10-20 every few seconds, and I must preserve their order. So, nanoseconds are important in this case (I write with another writer).

**Comment by offa** [comment]
> Since you're actually constructing a chrono object, it might be wise to actually convert the string directly without passing trough a tm structure.

That's true, but the only way to do this (at least I know) requires C++20.

**Comment by pquan** [comment]
I'm not sure if you prefer to not depend on external libraries. https://howardhinnant.github.io/date/date.html Is an example of a single header file library that does a lot of things, including conversion. 
It seems well written and requires C++11 or C++14 for best performance. But, in this simple case, parsing the final part of the timestamp returned by influx is sufficient. Timestring looks like `2021-05-04T06:00:01.219037Z`
and a simple search for the dot towards the Z shall be easy.
What concerns me is that all this is a performance nightmare. Those timestamps are already in long-ints inside influx. They're converted to UTC then passed to the client only to be converted back.

Maybe something along these lines is better?:
```
char *p = timeString.c_str() ;
int res = 0, d ;
while ( *p++ != '.');
while ( (d = *p++) != 'Z')
   res = res * 10 + d - '0' ;
mTimestamp += res ;
```

**Comment by offa** [comment]
Thanks for the suggestion, I'll have a look at it 👍. Especially if it's the pre-C++20 implementation, so we can switch to the STL version later easily.

> What concerns me is that all this is a performance nightmare. Those timestamps are already in long-ints inside influx. They're converted to UTC then passed to the client only to be converted back.

Indeed. A way to query the timestamp in an int type would be nice.

> Maybe something along these lines is better?:

No C code please.

**Comment by offa** [comment]
The *date* library looks promising. I have ported the time parsing on the `date_library` branch, which should support more precise timestamps now.

Could you test your use case with that version?

**Comment by pquan** [comment]
Ok, could not resist ;)

I can confirm that the conversion works on nanoseconds and on microseconds. Good job! 

Thank you and thanks to Howard Hinnant.

**Comment by offa** [comment]
Perfect, I'll merge to master and create a new release.
