### ISSUE TITLE
Support for Auth Token?

### ISSUE THREAD

**Issue by Pro** [offa/influxdb-cxx#90]
In Influx 2.0 the authentication is done via tokens.

https://docs.influxdata.com/influxdb/v2.0/write-data/developer-tools/api/#example-api-write-request

Is this somehow already supported in influxdb-cxx?

**Comment by offa** [comment]
Unfortunately no, only basic auth at the moment. v2.0 isn't supported yet, but It's planed for the future.

**Comment by alex-saoulis** [comment]
I will have a look at implementing this and contributing when I get the time. My only worry with `[protocol]://[auth_token@]host…]` was I don't know whether ':' is an allowed character in the auth_token, because if it is that would break the url parser. Do you have any idea if it is? 😃 I assume it's unlikely for exactly this issue it would cause.

**Comment by SimonEverts** [comment]
@offa maybe this will be helpfull too:
https://github.com/SimonEverts/influxdb-cxx/tree/feature/90-support-api-token

**Comment by offa** [comment]
Yes, it might be worth to add an additional API that enables programmatic setting of connection infos. Using an URL string becomes limiting at some point. 

While I'm not sure how to design the factory API yet (given, there are some different types transport), are you interested to submit the changes to `Transport` and `HTTP` (+ tests) as a PR already?

**Comment by kasparthommen** [comment]
Hi all, any news on this? What about merging the [proposed changes](https://github.com/offa/influxdb-cxx/issues/90#issuecomment-1119536966)?

**Comment by offa** [comment]
I'm going to implement basic url string based token support (as credentials are now). The linked changes aren't compatible anymore, the http backend has been replaced in the recent releases.

**Comment by offa** [comment]
PR is open (#214).

I had no opportunity to test it on a real database yet, if someone could give it a try.
