### ISSUE TITLE
Trompeloeil linking by CMake

### ISSUE THREAD

**Issue by RPatelski** [offa/influxdb-cxx#94]
In `test/CMakeLists.txt` and `test/mock/CMakeLists.txt` Trompeloeil is linked as `trompeloeil::trompeloeil`. This is not coherent with guides on the [Trompeloeil github page ](https://github.com/rollbear/trompeloeil/blob/main/docs/FAQ.md#cmake) where linking is done just by `trompeloeil`. I was unable to compile the test until I manually changed it from `trompeloeil::trompeloeil` to `trompeloeil` in both files. Is the current form correct and I installed something wrong or should it be changed to comply with naming shown on Trompeloeil page?

This my be related to #84 where author also struggled to install and link Trompeloeil.

**Comment by offa** [comment]
Interesting as an [alias target](https://github.com/rollbear/trompeloeil/blob/main/CMakeLists.txt#L17) is provided by trompeloeil. Can you check whether your version has it too? It was added a few months ago.

**Comment by RPatelski** [comment]
You are right in that, I can now see an alias target in the CMakeLists.txt of trompeloeil. Despite that, after the build it does not work. I can see that it is not getting into trompeloeil-targets.cmake (should it?) and I can make `trompeloeil::trompeloeil` work by maually adding  alias to this file (after already built and installed). May it be that there is some error in the Trompeloeil itself? I'm not very CMake-savvy, so if the current version is theoretically fine, then we can let it be.

**Comment by offa** [comment]
It turned out there's an alias target but `trompeloeil::trompeloeil` isn't installed actually. I have opened an issue upstream (https://github.com/rollbear/trompeloeil/issues/242) and add the target in the meantime.

**Comment by offa** [comment]
Now, since GH Actions are working again, the workaround is on master. Please let me know if there are any issues.

**Comment by RPatelski** [comment]
Thanks, everything seems to be working fine now.

**Comment by offa** [comment]
Perfect! The missing target will be included in the next trompeloeil release.
